### ISSUE TITLE
"Received empty string in response!"

### ISSUE THREAD

**Issue by Liuk-ITA** [robotzero1/esp32cam-telegram#1]
hi, I've tryed the TelegramSendPhotoChunked1_2.ino file, and it works, but very often in the serial monitor I get "Received empty string in response!",

when it works (one time every 10 cicles):
```
GET Update Messages
[BOT]Connecting to server
.... connected to server

{"ok":true,"result":[]}⸮

incoming message length 24
Creating DynamicJsonBuffer
GetUpdates parsed jsonDoc: {"ok":true,"result":[]}
GetUpdates parsed jsonObj: {"ok":true,"result":[]}
no new messages

```

very often:
```
- GET Update Messages
- [BOT]Connecting to server
- .... connected to server
**- Received empty string in response!**
- Closing client

```

In addition, after this procedure is completed
```
[...]
Sending binary photo full buffer
Sending binary photo full buffer
Sending binary photo remaining buffer
End request: 
--------------------------b8f610217e83e29b--
Closing client

```
I get no photo on telegram...

It is only me getting this problems? thanks!

p.s.: thanks for the work you've done since now!

**Comment by robotzero1** [comment]
Hi,
Can you try changing the line
  `s->set_framesize(s, FRAMESIZE_XGA);`
to
  `s->set_framesize(s, FRAMESIZE_VGA);`
I'm not sure but I think the SSL part of the transaction is fragmenting the memory.

**Comment by Liuk-ITA** [comment]
thanks, now I realized that this happen when I changed the code to use multiple wifi network, with the WifiMulti.h library: https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFi/examples/WiFiMulti/WiFiMulti.ino
